// ─── Types ─────────────────────────────────────────────────────────────────────
export type ContentBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "ol"; items: string[] }
  | { type: "steps"; items: { title: string; desc: string }[] }
  | { type: "tip"; text: string }
  | { type: "warning"; text: string }

export type ArtigoData = {
  slug: string
  titulo: string
  tags: string[]
  resumo: string
  tempoLeitura: number
  conteudo: ContentBlock[]
}

export type CategoriaData = {
  slug: string
  titulo: string
  descricao: string
  cor: string
  corBg: string
  icon: string
  aspectW: number
  aspectH: number
  artigos: ArtigoData[]
}

// ─── Categoria: Produtos ────────────────────────────────────────────────────────
const artigos_produtos: ArtigoData[] = [
  {
    slug: "diferenca-essentials-e-premium",
    titulo: "Qual a diferença entre Linha Neo Essentials e Premium?",
    tags: ["Linha Neo", "Comparativo"],
    resumo: "Entenda as principais diferenças entre as linhas Neo Essentials e Neo Premium para escolher o purificador ideal para você.",
    tempoLeitura: 4,
    conteudo: [
      { type: "p", text: "A Acquafy oferece dois grandes grupos de purificadores inteligentes: a linha Neo Essentials e a linha Neo Premium. Embora compartilhem a base tecnológica de conectividade Wi-Fi 5, Bluetooth 5.3 e App Acquafy, elas se diferenciam em público-alvo, tecnologia de filtração e nível de acabamento." },
      { type: "h2", text: "Neo Essentials" },
      { type: "p", text: "Focada em custo-benefício, a linha Essentials inclui os modelos Neo UP, FIT, SMART H₂, TOUCH, PLUS, ULTRA e MAX. Todos utilizam filtração por UV LED + Ultrafiltração (UF) com 4 filtros de alta performance, oferecendo proteção eficiente contra bactérias, vírus e partículas." },
      { type: "ul", items: [
        "Painel LED Touch 10.1\" com contagem regressiva de filtros",
        "Filtração UV LED + UF — 20+ etapas de tratamento",
        "Conectividade Wi-Fi 5 e Bluetooth 5.3",
        "App Acquafy com IA integrada",
        "Modelos compactos (bancada ou parede)",
        "Opções com água com gás (Spark) e hidrogenada (H₂)",
      ]},
      { type: "h2", text: "Neo Premium" },
      { type: "p", text: "A linha Premium — modelos INFINITY, PRESTIGE e PRIME — foi desenvolvida para quem busca o mais alto padrão de purificação e design. Ela incorpora tecnologia de Osmose Reversa (RO) alcalina, mais rigorosa que a UF, e um painel IPS 15.6\" de alta resolução." },
      { type: "ul", items: [
        "Painel IPS 15.6\" com interface ampliada",
        "Filtração por Osmose Reversa (RO) alcalina — remoção superior de contaminantes",
        "Acabamento de alto padrão em policarbonato e aço inoxidável",
        "Disponível em versões Spark (água com gás) e Spark H₂ (água hidrogenada)",
        "Ideal para uso em ambientes corporativos e residências premium",
      ]},
      { type: "h2", text: "Resumo comparativo" },
      { type: "ul", items: [
        "Essentials: painel 10.1\", UV LED + UF, custo-benefício",
        "Premium: painel 15.6\", Osmose Reversa (RO), alto padrão",
        "Ambas: Wi-Fi 5, Bluetooth 5.3, App Acquafy, IA integrada",
      ]},
      { type: "tip", text: "Se você busca um purificador confiável para uso residencial ou em pequenos negócios, a linha Essentials atende perfeitamente. Para ambientes exigentes ou com maior variação na qualidade da água, a linha Premium com RO é a escolha ideal." },
    ],
  },
  {
    slug: "tipos-de-agua-que-o-neo-fornece",
    titulo: "Quais tipos de água o purificador Neo fornece?",
    tags: ["Água", "Filtração"],
    resumo: "Conheça todos os tipos de água disponíveis nos diferentes modelos da linha Neo, de natural e gelada a hidrogenada e com gás.",
    tempoLeitura: 3,
    conteudo: [
      { type: "p", text: "Os purificadores Neo oferecem diferentes combinações de tipos de água dependendo do modelo escolhido. Confira abaixo quais são os tipos disponíveis e em quais modelos cada um está presente." },
      { type: "h2", text: "Tipos de água disponíveis" },
      { type: "ul", items: [
        "Água Natural — presente em todos os modelos",
        "Água Gelada — presente em todos os modelos, exceto o Neo SMART H₂",
        "45°C (Leite) — presente em todos os modelos",
        "65°C (Chá) — presente em todos os modelos",
        "100°C (Café) — presente em todos os modelos",
        "Água com Gás — exclusivo nos modelos 6 em 1 (Spark) e 7 em 1 (Spark H₂)",
        "Água Hidrogenada H₂ — exclusivo nos modelos 7 em 1 (Spark H₂) e Neo SMART H₂",
      ]},
      { type: "h2", text: "Modelos e suas funções" },
      { type: "ul", items: [
        "Neo UP: apenas água natural (1 função)",
        "Neo FIT, TOUCH, PLUS, ULTRA, MAX: 5 em 1 (natural, gelada, 45°, 65°, 100°)",
        "Neo SMART H₂: 5 em 1 com hidrogenada (natural, 45°, 65°, 100°, H₂)",
        "Modelos SPARK: 6 em 1 (5 em 1 + com gás)",
        "Modelos SPARK H₂: 7 em 1 (5 em 1 + com gás + H₂)",
      ]},
      { type: "h2", text: "Sobre a água hidrogenada" },
      { type: "p", text: "A água hidrogenada é enriquecida com hidrogênio molecular (H₂), reconhecido por propriedades antioxidantes. É uma opção crescente entre pessoas que buscam bem-estar e qualidade de vida." },
      { type: "tip", text: "Para famílias que desejam versatilidade máxima, os modelos 7 em 1 (Spark H₂) oferecem todas as temperaturas, água com gás e água hidrogenada em um único equipamento." },
    ],
  },
  {
    slug: "como-verificar-garantia-do-produto",
    titulo: "Como verificar a garantia do meu produto?",
    tags: ["Garantia", "Registro"],
    resumo: "Saiba como registrar e verificar a garantia do seu purificador Neo pelo aplicativo ou portal de suporte.",
    tempoLeitura: 3,
    conteudo: [
      { type: "p", text: "Os purificadores Neo possuem garantia de 1 ano contra defeitos de fabricação a partir da data de compra. Para usufruir da garantia, é necessário registrar o produto." },
      { type: "h2", text: "Como registrar a garantia" },
      { type: "steps", items: [
        { title: "Baixe o aplicativo Acquafy", desc: "Disponível gratuitamente na App Store (iOS) e Google Play (Android)." },
        { title: "Crie ou acesse sua conta", desc: "Use o e-mail cadastrado no momento da compra." },
        { title: "Adicione seu dispositivo", desc: "Aproxime o smartphone do purificador via Bluetooth 5.3 e siga o assistente de configuração." },
        { title: "Confirme o registro", desc: "O número de série será validado automaticamente e a garantia ativada." },
      ]},
      { type: "h2", text: "O que está coberto pela garantia" },
      { type: "ul", items: [
        "Defeitos de fabricação no gabinete e componentes elétricos",
        "Falhas no painel LED/IPS sob uso normal",
        "Problemas no sistema de filtração por defeito do fabricante",
        "Problemas de conectividade Wi-Fi ou Bluetooth por defeito de fábrica",
      ]},
      { type: "h2", text: "O que NÃO está coberto" },
      { type: "ul", items: [
        "Danos causados por instalação incorreta",
        "Uso inadequado ou fora das especificações técnicas",
        "Manutenção negligenciada (como não troca do filtro nos 365 dias)",
        "Danos físicos por quedas, impactos ou infiltrações",
        "Desgaste natural de consumíveis (filtros, selos)",
      ]},
      { type: "warning", text: "A garantia é válida apenas para produtos comprados por canais autorizados Acquafy. Guarde o comprovante de compra." },
    ],
  },
  {
    slug: "tecnologia-uv-led-uf-no-neo",
    titulo: "O que é a tecnologia UV LED + UF no Neo?",
    tags: ["Tecnologia", "Filtração"],
    resumo: "Descubra como funciona a dupla de purificação UV LED e Ultrafiltração (UF) que equipa os modelos da linha Neo Essentials.",
    tempoLeitura: 4,
    conteudo: [
      { type: "p", text: "Os purificadores da linha Neo Essentials utilizam a combinação de UV LED (luz ultravioleta de alta eficiência) com filtração por UF (Ultrafiltração), formando um sistema de 20+ etapas de tratamento de água que garante qualidade sem uso de produtos químicos." },
      { type: "h2", text: "UV LED — esterilização por luz ultravioleta" },
      { type: "p", text: "A tecnologia UV LED emite radiação ultravioleta em comprimento de onda específico (254nm) que destrói o DNA de microrganismos como bactérias, vírus e protozoários, tornando-os incapazes de se reproduzir. Por ser baseada em luz, não altera o sabor, o odor ou o pH da água." },
      { type: "ul", items: [
        "Elimina 99,99% das bactérias e vírus presentes na água",
        "Sem cloro ou outros produtos químicos",
        "Ativação instantânea — sem tempo de espera",
        "Vida útil de aproximadamente 10.000 horas",
        "Econômico em energia elétrica",
      ]},
      { type: "h2", text: "UF — Ultrafiltração por membrana" },
      { type: "p", text: "A Ultrafiltração é um processo de filtração física por membrana com poros de 0,01 micron. Ela remove partículas em suspensão, cis­tos de protozoários, bactérias e macromoléculas, mantendo na água os minerais essenciais." },
      { type: "ul", items: [
        "Remove partículas, sedimentos e turbidez",
        "Retém cistos de Giardia e Cryptosporidium",
        "Preserva sais minerais benéficos à saúde",
        "Não requer eletricidade adicional para a membrana",
      ]},
      { type: "h2", text: "A linha Premium usa Osmose Reversa (RO)" },
      { type: "p", text: "Os modelos da linha Premium (INFINITY, PRESTIGE, PRIME) utilizam Osmose Reversa Alcalina, que adiciona uma etapa de remineralização após a filtração RO, elevando o pH da água para um nível levemente alcalino (7,5–8,5)." },
      { type: "tip", text: "Para água de rede municipal com controle de qualidade, a tecnologia UV LED + UF dos modelos Essentials é altamente eficaz e suficiente para uso seguro diário." },
    ],
  },
  {
    slug: "especificacoes-painel-led-10-e-15",
    titulo: "Especificações técnicas do painel LED 10.1\" e 15.6\"",
    tags: ["Especificações", "Hardware"],
    resumo: "Conheça as funcionalidades e especificações dos painéis de toque inteligentes presentes nos purificadores Neo Essentials (10.1\") e Neo Premium (15.6\").",
    tempoLeitura: 3,
    conteudo: [
      { type: "h2", text: "Painel LED Touch 10.1\" — Neo Essentials" },
      { type: "p", text: "Presente em todos os modelos Essentials com conectividade (exceto o Neo UP), o painel de 10.1\" é o centro de controle do purificador e também a superfície de exibição do Acquafy Media." },
      { type: "ul", items: [
        "Tela LED Touch capacitivo de 10,1 polegadas",
        "Contagem regressiva de 365 dias até a troca dos filtros",
        "Relógio digital com data e hora",
        "Status da água em tempo real",
        "Alertas inteligentes (filtro, temperatura, conectividade)",
        "Comunicação bidirecional com o App Acquafy e IA",
        "Exibição de campanhas e QR Codes via Acquafy Media",
      ]},
      { type: "h2", text: "Painel IPS 15.6\" — Neo Premium" },
      { type: "p", text: "Os modelos da linha Premium contam com uma tela IPS de 15,6 polegadas, maior brilho, ângulo de visão ampliado e maior área para exibição de conteúdo Acquafy Media." },
      { type: "ul", items: [
        "Tela IPS 15,6\" — brilho e cores superiores ao LED padrão",
        "Ângulo de visão de 178° (IPS)",
        "Todas as funções do painel 10.1\" com interface expandida",
        "Maior área de exibição de campanhas e QR Codes",
        "Ideal para ambientes com alto fluxo de pessoas",
      ]},
      { type: "tip", text: "O tamanho da tela influencia diretamente na receita potencial do Acquafy Media: uma tela maior exibe conteúdo com mais destaque e atrai mais interações via QR Code." },
    ],
  },
  {
    slug: "qual-modelo-escolher-fit-smart-ultra",
    titulo: "Qual modelo escolher: Neo FIT, SMART H₂ ou ULTRA?",
    tags: ["Comparativo", "Guia"],
    resumo: "Guia prático para escolher entre os modelos Neo FIT, SMART H₂ e ULTRA conforme seu perfil de uso e necessidades.",
    tempoLeitura: 4,
    conteudo: [
      { type: "p", text: "Com múltiplos modelos disponíveis, a Acquafy facilita a escolha com este guia comparativo entre os três modelos mais populares da linha Essentials." },
      { type: "h2", text: "Neo FIT — compacto e versátil" },
      { type: "ul", items: [
        "5 funções: natural, gelada, 45°C, 65°C, 100°C",
        "Tanque interno de 400ml",
        "Painel LED Touch 10.1\"",
        "Formato bancada ou parede",
        "Ideal para: escritórios, apartamentos, uso individual",
        "Preço: US$ 497.97",
      ]},
      { type: "h2", text: "Neo SMART H₂ — hidrogenada integrada" },
      { type: "ul", items: [
        "5 funções: natural, 45°C, 65°C, 100°C e Água Hidrogenada H₂",
        "Sem tanque de água gelada (foca na H₂)",
        "Painel LED Touch 10.1\"",
        "Ideal para: usuários focados em bem-estar e saúde",
        "Preço: US$ 597.97",
      ]},
      { type: "h2", text: "Neo ULTRA — alta capacidade" },
      { type: "ul", items: [
        "Disponível em 5, 6 ou 7 funções (ULTRA, ULTRA SPARK, ULTRA SPARK H₂)",
        "Tanque interno de 3L",
        "Painel LED Touch 10.1\"",
        "Ideal para: famílias, cozinhas movimentadas, alto consumo",
        "Versão SPARK inclui água com gás; SPARK H₂ adiciona hidrogenada",
      ]},
      { type: "h2", text: "Como escolher" },
      { type: "ul", items: [
        "Espaço reduzido ou uso individual → Neo FIT",
        "Prioridade em saúde e hidratação → Neo SMART H₂",
        "Família ou uso intenso → Neo ULTRA",
        "Família + água com gás → Neo ULTRA SPARK",
        "Família + máxima versatilidade → Neo ULTRA SPARK H₂",
      ]},
      { type: "tip", text: "Acesse a página de comparação do site Acquafy para ver uma tabela completa com todos os modelos lado a lado." },
    ],
  },
]

// ─── Categoria: App + AI + IoT ───────────────────────────────────────────────────
const artigos_app_ai_iot: ArtigoData[] = [
  {
    slug: "como-configurar-wifi-no-neo",
    titulo: "Como configurar o Wi-Fi no purificador Neo?",
    tags: ["Wi-Fi", "Configuração"],
    resumo: "Passo a passo para conectar seu purificador Neo à rede Wi-Fi usando o aplicativo Acquafy.",
    tempoLeitura: 3,
    conteudo: [
      { type: "p", text: "Conectar o seu purificador Neo ao Wi-Fi permite acesso remoto completo, recebimento de alertas em tempo real e integração com a IA Acquafy. O processo é rápido e guiado pelo próprio aplicativo." },
      { type: "h2", text: "Pré-requisitos" },
      { type: "ul", items: [
        "Smartphone com iOS 14+ ou Android 8.0+",
        "Aplicativo Acquafy instalado e conta criada",
        "Rede Wi-Fi 5 disponível (2,4 GHz ou 5 GHz)",
        "Purificador Neo ligado e próximo ao roteador",
      ]},
      { type: "h2", text: "Passo a passo" },
      { type: "steps", items: [
        { title: "Abra o aplicativo Acquafy", desc: "Faça login na sua conta." },
        { title: "Acesse a seção Dispositivos", desc: "Toque em \"Adicionar dispositivo\" no canto superior direito." },
        { title: "Selecione seu modelo", desc: "Escolha o modelo correto na lista da linha Neo." },
        { title: "Conecte via Bluetooth 5.3", desc: "Aproxime o celular do purificador. O app identificará automaticamente o dispositivo." },
        { title: "Configure o Wi-Fi", desc: "Selecione sua rede Wi-Fi, insira a senha e confirme. O purificador se conectará em até 30 segundos." },
      ]},
      { type: "h2", text: "Solução de problemas" },
      { type: "ul", items: [
        "Purificador não aparece no Bluetooth: verifique se o Bluetooth do celular está ativado e aproxime mais o dispositivo.",
        "Falha ao conectar ao Wi-Fi: confirme a senha e verifique se está na rede correta (2,4 GHz ou 5 GHz).",
        "Conexão cai frequentemente: posicione o purificador mais próximo ao roteador ou use um repetidor Wi-Fi.",
        "Resetar Wi-Fi: no painel do purificador, acesse Configurações > Rede > Redefinir Wi-Fi.",
      ]},
      { type: "tip", text: "Para melhor desempenho, prefira posicionar o purificador a até 10 metros do roteador, sem paredes grossas entre eles." },
    ],
  },
  {
    slug: "como-usar-aplicativo-acquafy",
    titulo: "Como usar o aplicativo Acquafy no celular?",
    tags: ["App", "Tutorial"],
    resumo: "Guia completo sobre como instalar, configurar e aproveitar todas as funções do aplicativo Acquafy.",
    tempoLeitura: 4,
    conteudo: [
      { type: "p", text: "O aplicativo Acquafy é o centro de controle do seu purificador Neo. Por ele você monitora a qualidade da água, recebe alertas, solicita suporte com IA e gerencia seus dispositivos." },
      { type: "h2", text: "Como instalar" },
      { type: "steps", items: [
        { title: "App Store ou Google Play", desc: "Busque por \"Acquafy\" na loja do seu sistema operacional e instale gratuitamente." },
        { title: "Crie sua conta", desc: "Informe nome, e-mail e senha. Confirme o e-mail de verificação." },
        { title: "Adicione seu purificador", desc: "Com o Bluetooth ativado, siga o assistente de configuração para vincular o dispositivo." },
      ]},
      { type: "h2", text: "Principais seções do app" },
      { type: "ul", items: [
        "Início: painel com status do purificador, qualidade da água e alertas recentes",
        "Dispositivos: lista de purificadores vinculados, status online/offline, estatísticas de uso",
        "Aquafy AI: chat com inteligência artificial para dúvidas, diagnósticos e recomendações",
        "Filtros: vida útil dos filtros com barra de progresso e opção de pedido via app",
        "Suporte: acesso rápido a manuais, tutoriais e abertura de chamados",
        "Configurações: perfil, notificações, idioma e gerenciamento de conta",
      ]},
      { type: "h2", text: "Notificações inteligentes" },
      { type: "p", text: "O app envia notificações automáticas para: troca iminente de filtro (30, 7 e 1 dia antes), alertas de qualidade de água, dispositivo offline, e novidades de produtos." },
      { type: "tip", text: "Ative as notificações push do app para garantir que você não perca nenhum alerta importante sobre o seu purificador." },
    ],
  },
  {
    slug: "o-que-e-suporte-ia-24-7",
    titulo: "O que é o suporte por IA 24/7?",
    tags: ["IA", "Suporte"],
    resumo: "Entenda como a inteligência artificial integrada ao app Acquafy oferece suporte personalizado e proativo a qualquer hora do dia.",
    tempoLeitura: 3,
    conteudo: [
      { type: "p", text: "A Acquafy AI é uma inteligência artificial integrada ao aplicativo que aprende com o uso do seu purificador, monitora dados em tempo real e oferece suporte especializado disponível 24 horas por dia, 7 dias por semana." },
      { type: "h2", text: "O que a IA faz pelo seu purificador" },
      { type: "ul", items: [
        "Gera insights automáticos e preditivos sobre o desempenho do equipamento",
        "Faz recomendações personalizadas com base no seu perfil de consumo",
        "Detecta padrões de uso e anomalias operacionais antes que virem problemas",
        "Cria resumos inteligentes da operação do purificador",
        "Responde perguntas técnicas e de uso via chat no app",
        "Monitora o ciclo de vida dos filtros e sugere momento ideal de troca",
      ]},
      { type: "h2", text: "Como acessar o suporte por IA" },
      { type: "steps", items: [
        { title: "Abra o aplicativo Acquafy", desc: "Na barra de navegação inferior, toque em \"Acquafy AI\"." },
        { title: "Digite sua dúvida", desc: "A IA responde em texto e, quando necessário, com guias visuais." },
        { title: "Receba diagnóstico", desc: "Para problemas no equipamento, a IA analisa dados do dispositivo em tempo real." },
        { title: "Escalone se necessário", desc: "Se a IA não resolver, ela abre automaticamente um chamado para a equipe técnica humana." },
      ]},
      { type: "tip", text: "A IA aprende com o uso: quanto mais você a consulta, mais precisa ela fica para o seu perfil e equipamento específico." },
    ],
  },
  {
    slug: "como-monitorar-qualidade-da-agua",
    titulo: "Como monitorar a qualidade da água pelo app?",
    tags: ["IoT", "Monitoramento"],
    resumo: "Aprenda a usar os recursos de monitoramento em tempo real do app Acquafy para acompanhar a qualidade da água do seu purificador.",
    tempoLeitura: 3,
    conteudo: [
      { type: "p", text: "O purificador Neo conta com sensores IoT integrados que enviam dados de qualidade da água ao aplicativo Acquafy em tempo real. Você pode acompanhar tudo pelo celular, mesmo a distância." },
      { type: "h2", text: "Indicadores monitorados" },
      { type: "ul", items: [
        "Status geral da água (boa, atenção, crítica)",
        "Temperatura de cada saída (natural, gelada, quente)",
        "Ciclo dos filtros: percentual de vida útil restante",
        "Status da lâmpada UV LED",
        "Histórico de consumo diário/semanal/mensal (em litros)",
        "Tempo de uso e número de dispensas",
      ]},
      { type: "h2", text: "Como acessar os dados" },
      { type: "steps", items: [
        { title: "Abra o app e vá em Dispositivos", desc: "Selecione o purificador desejado." },
        { title: "Veja o painel de status", desc: "A tela inicial exibe um resumo visual com os principais indicadores." },
        { title: "Toque em \"Ver detalhes\"", desc: "Acesse dados expandidos com gráficos de consumo e histórico de alertas." },
      ]},
      { type: "h2", text: "Alertas automáticos" },
      { type: "p", text: "O sistema envia notificações push quando identifica: qualidade de água abaixo do padrão, filtro próximo do vencimento, temperatura fora do range ideal ou dispositivo offline há mais de 1 hora." },
      { type: "warning", text: "Se o indicador de qualidade mostrar alerta vermelho, evite consumir a água até verificar o filtro e entrar em contato com o suporte." },
    ],
  },
  {
    slug: "compatibilidade-ios-android",
    titulo: "Compatibilidade com iOS e Android",
    tags: ["App", "Compatibilidade"],
    resumo: "Verifique os requisitos mínimos de sistema operacional para usar o aplicativo Acquafy no seu smartphone.",
    tempoLeitura: 2,
    conteudo: [
      { type: "p", text: "O aplicativo Acquafy é compatível com as principais versões do iOS (Apple) e Android (Google). Confira os requisitos mínimos abaixo." },
      { type: "h2", text: "iOS (Apple)" },
      { type: "ul", items: [
        "Versão mínima: iOS 14.0 ou superior",
        "Dispositivos compatíveis: iPhone 6s e modelos posteriores",
        "Download: App Store",
        "Bluetooth 5.0+ necessário para emparelhamento direto",
      ]},
      { type: "h2", text: "Android (Google)" },
      { type: "ul", items: [
        "Versão mínima: Android 8.0 (Oreo) ou superior",
        "Dispositivos compatíveis: a maioria dos smartphones Android modernos",
        "Download: Google Play Store",
        "Bluetooth 5.0+ recomendado para melhor desempenho",
      ]},
      { type: "h2", text: "Requisitos gerais" },
      { type: "ul", items: [
        "Conexão à internet para sincronização de dados e IA",
        "Bluetooth habilitado para configuração inicial e controle local",
        "Notificações push ativadas para alertas em tempo real",
        "Armazenamento mínimo: 80MB livres no dispositivo",
      ]},
      { type: "tip", text: "Para garantir todas as funcionalidades de IA e monitoramento, mantenha o aplicativo sempre atualizado para a versão mais recente disponível na loja." },
    ],
  },
  {
    slug: "configurar-bluetooth-5-3",
    titulo: "Configuração do Bluetooth 5.3 para controle local",
    tags: ["Bluetooth", "Configuração"],
    resumo: "Aprenda a usar o Bluetooth 5.3 do purificador Neo para controle e configuração local, mesmo sem internet.",
    tempoLeitura: 3,
    conteudo: [
      { type: "p", text: "O purificador Neo inclui Bluetooth 5.3, que permite comunicação direta com o smartphone sem depender de Wi-Fi ou conexão à internet. Esse recurso é essencial para a configuração inicial e para uso em locais sem sinal de rede." },
      { type: "h2", text: "Para que serve o Bluetooth 5.3" },
      { type: "ul", items: [
        "Configuração inicial do Wi-Fi (assistente guiado)",
        "Controle local quando não há internet disponível",
        "Sincronização rápida de dados ao aproximar o celular",
        "Diagnóstico técnico sem necessidade de rede",
        "Alcance de até 10 metros em linha direta",
      ]},
      { type: "h2", text: "Como emparelhar o dispositivo" },
      { type: "steps", items: [
        { title: "Ative o Bluetooth no celular", desc: "Vá em Configurações > Bluetooth e certifique-se de que está habilitado." },
        { title: "Abra o app Acquafy", desc: "Toque em \"Dispositivos\" e depois em \"Adicionar dispositivo\"." },
        { title: "Aproxime o celular do purificador", desc: "Fique a até 2 metros de distância para melhor detecção." },
        { title: "Confirme o emparelhamento", desc: "O app exibirá o modelo detectado. Confirme para concluir." },
      ]},
      { type: "h2", text: "Solução de problemas" },
      { type: "ul", items: [
        "App não detecta o purificador: desative e reative o Bluetooth no celular.",
        "Emparelhamento falha repetidamente: no painel do purificador, vá em Configurações > Bluetooth > Redefinir.",
        "Sinal fraco: remova obstáculos metálicos ou paredes espessas entre o celular e o purificador.",
      ]},
    ],
  },
]

// ─── Categoria: Media Network ────────────────────────────────────────────────────
const artigos_media_network: ArtigoData[] = [
  {
    slug: "como-funciona-sistema-de-anuncios",
    titulo: "Como funciona o sistema de anúncios na tela?",
    tags: ["Anúncios", "Receita"],
    resumo: "Entenda como o Acquafy Media transforma a tela touchscreen do purificador em um canal de publicidade e geração de receita.",
    tempoLeitura: 3,
    conteudo: [
      { type: "p", text: "O Acquafy Media é uma plataforma de mídia integrada ao painel touchscreen dos purificadores Neo. Enquanto o equipamento está em uso, a tela exibe campanhas publicitárias de negócios locais — criando um canal de mídia contextual de alto engajamento." },
      { type: "h2", text: "Como funciona na prática" },
      { type: "steps", items: [
        { title: "Instale o Acquafy Media", desc: "O parceiro Gold configura o sistema via plataforma Acquafy. A integração com o purificador é automática." },
        { title: "Campanhas são exibidas", desc: "Anúncios de negócios locais (restaurantes, clínicas, academias, etc.) aparecem na tela de forma inteligente e contextual." },
        { title: "QR Codes geram ação", desc: "O usuário escaneia o QR Code exibido na tela com o celular para acessar promoções, cardápios, sites ou formulários." },
        { title: "IA monitora a performance", desc: "Dados de engajamento, scans e conversões são coletados e disponibilizados em tempo real." },
        { title: "Receita recorrente", desc: "O parceiro Gold recebe mensalmente pela exibição das campanhas e pelas vendas de Neo que fizer via link/QR Code próprio." },
      ]},
      { type: "h2", text: "Onde o Acquafy Media pode ser instalado" },
      { type: "ul", items: [
        "Academias, spas e centros de bem-estar",
        "Restaurantes, cafés e lanchonetes",
        "Clínicas médicas e odontológicas",
        "Hotéis, pousadas e resorts",
        "Escritórios corporativos com alto fluxo",
        "Shopping centers e lobbies comerciais",
      ]},
      { type: "tip", text: "Locais com alto fluxo de pessoas maximizam o potencial de exibição e, consequentemente, a receita do parceiro Gold." },
    ],
  },
  {
    slug: "como-cadastrar-campanha-acquafy-media",
    titulo: "Como cadastrar uma campanha no Acquafy Media?",
    tags: ["Campanha", "Tutorial"],
    resumo: "Passo a passo para anunciantes criarem e publicarem campanhas na rede Acquafy Media.",
    tempoLeitura: 4,
    conteudo: [
      { type: "p", text: "Qualquer negócio pode anunciar na rede Acquafy Media, alcançando consumidores no momento em que interagem com o purificador. O processo de cadastro de campanha é direto pela plataforma Acquafy." },
      { type: "h2", text: "Passo a passo para criar uma campanha" },
      { type: "steps", items: [
        { title: "Acesse a plataforma Acquafy Media", desc: "Entre com suas credenciais de anunciante em media.acquafy.com." },
        { title: "Crie sua conta de anunciante", desc: "Informe dados da empresa, responsável e informações de pagamento." },
        { title: "Clique em \"Nova campanha\"", desc: "Dê um nome descritivo e defina o objetivo (tráfego, vendas, awareness)." },
        { title: "Faça upload dos materiais criativos", desc: "Envie as imagens ou vídeos no formato e dimensões aceitos pela plataforma." },
        { title: "Configure período e localização", desc: "Defina datas de início e fim e selecione os pontos (purificadores) onde a campanha será exibida." },
        { title: "Defina o orçamento", desc: "Configure o valor diário ou total da campanha e forma de pagamento." },
        { title: "Revise e publique", desc: "Após a revisão, a campanha passa por aprovação (até 24h) e entra no ar automaticamente." },
      ]},
      { type: "h2", text: "Dicas para uma campanha eficiente" },
      { type: "ul", items: [
        "Use imagens de alta resolução com mensagem clara e objetiva",
        "Inclua um QR Code com destino direto (não links genéricos)",
        "Mensagens curtas têm melhor performance em telas de purificadores",
        "Prefira cores contrastantes para garantir leitura em diferentes iluminações",
      ]},
      { type: "tip", text: "Anunciantes com QR Codes ativos nas campanhas registram, em média, 3× mais conversões do que campanhas apenas de imagem." },
    ],
  },
  {
    slug: "o-que-e-qr-code-de-campanha",
    titulo: "O que é o QR Code de campanha e como usar?",
    tags: ["QR Code", "Marketing"],
    resumo: "Entenda como os QR Codes dinâmicos do Acquafy Media transformam visualizações em ações concretas do usuário.",
    tempoLeitura: 3,
    conteudo: [
      { type: "p", text: "O QR Code de campanha é um código QR dinâmico exibido ao lado do anúncio na tela do purificador Neo. Quando o usuário escaneia com a câmera do celular, é direcionado para um destino definido pelo anunciante." },
      { type: "h2", text: "O que o QR Code pode fazer" },
      { type: "ul", items: [
        "Redirecionar para site ou landing page do anunciante",
        "Abrir cardápio digital de restaurante",
        "Exibir cupom de desconto resgatável no caixa",
        "Iniciar conversa no WhatsApp Business",
        "Direcionar para formulário de cadastro ou agendamento",
        "Exibir vídeo promocional ou menu de opções",
      ]},
      { type: "h2", text: "QR Codes dinâmicos vs. estáticos" },
      { type: "p", text: "O Acquafy Media utiliza QR Codes dinâmicos, cujo destino pode ser alterado sem gerar um novo código. Isso permite que o anunciante mude a promoção ou o link sem precisar reenviar o material criativo." },
      { type: "h2", text: "Como acompanhar os scans" },
      { type: "ul", items: [
        "Acesse o painel de campanha na plataforma Acquafy Media",
        "Veja o número total de scans por dia/semana/mês",
        "Identifique horários de pico de interação",
        "Analise taxa de conversão (scans × ações realizadas)",
      ]},
      { type: "tip", text: "Posicione o QR Code sempre na área central inferior da arte, onde o olhar do usuário naturalmente pousa ao olhar para a tela enquanto aguarda a água." },
    ],
  },
  {
    slug: "calcular-receita-recorrente-com-media",
    titulo: "Como calcular a receita recorrente com Media?",
    tags: ["Receita", "Negócio"],
    resumo: "Aprenda como estimar e maximizar a receita mensal de um parceiro Gold operando o Acquafy Media.",
    tempoLeitura: 4,
    conteudo: [
      { type: "p", text: "O parceiro Gold da Acquafy possui duas fontes principais de receita: a monetização da mídia exibida na tela do purificador e as comissões sobre vendas de produtos Neo realizadas por meio do seu link ou QR Code exclusivo." },
      { type: "h2", text: "Fonte 1 — Receita de mídia" },
      { type: "p", text: "Negócios locais pagam mensalmente para anunciar na rede do parceiro Gold. O parceiro define os preços das campanhas em seu ponto de hidratação com base no fluxo de pessoas e no perfil do local." },
      { type: "ul", items: [
        "Receita variável de acordo com o volume de anunciantes",
        "Modelo flexível: por exibição, por período ou por resultado",
        "Quanto maior o fluxo de pessoas no ponto, maior o valor de anúncio",
        "Potencial de múltiplos anunciantes simultâneos em rotação",
      ]},
      { type: "h2", text: "Fonte 2 — Comissão sobre vendas Neo" },
      { type: "p", text: "Ao compartilhar o link ou QR Code exclusivo com clientes ou na própria tela do purificador, o parceiro Gold recebe 20% de comissão sobre cada venda concluída." },
      { type: "h2", text: "Exemplo ilustrativo" },
      { type: "ul", items: [
        "1 purificador em academia com 200 acessos/dia",
        "3 anunciantes locais pagando em média US$ 150/mês cada",
        "Receita de mídia: US$ 450/mês",
        "2 vendas Neo/mês via QR Code (comissão de US$ 100/venda): US$ 200/mês",
        "Total estimado: US$ 650/mês por ponto de hidratação",
      ]},
      { type: "tip", text: "Parceiros Gold com múltiplos purificadores instalados em pontos diferentes multiplicam sua receita a cada novo equipamento ativo." },
    ],
  },
  {
    slug: "formatos-e-dimensoes-para-anuncios",
    titulo: "Formatos e dimensões aceitos para anúncios",
    tags: ["Design", "Especificações"],
    resumo: "Especificações técnicas de formatos, dimensões e tamanhos de arquivo aceitos para campanhas no Acquafy Media.",
    tempoLeitura: 3,
    conteudo: [
      { type: "p", text: "Para garantir que seus anúncios sejam exibidos com qualidade nas telas dos purificadores Neo, siga as especificações técnicas abaixo." },
      { type: "h2", text: "Tela 10.1\" — Neo Essentials" },
      { type: "ul", items: [
        "Resolução recomendada: 1280 × 800px (ou 1024 × 600px)",
        "Proporção: 16:10",
        "Formatos aceitos: JPEG, PNG, MP4",
        "Tamanho máximo de imagem: 5MB",
        "Tamanho máximo de vídeo: 30MB",
        "Duração máxima de vídeo: 30 segundos",
      ]},
      { type: "h2", text: "Tela 15.6\" — Neo Premium" },
      { type: "ul", items: [
        "Resolução recomendada: 1920 × 1080px (Full HD)",
        "Proporção: 16:9",
        "Formatos aceitos: JPEG, PNG, MP4",
        "Tamanho máximo de imagem: 10MB",
        "Tamanho máximo de vídeo: 50MB",
        "Duração máxima de vídeo: 30 segundos",
      ]},
      { type: "h2", text: "Boas práticas de design" },
      { type: "ul", items: [
        "Use fundo contrastante — evite branco sobre branco ou preto total",
        "Texto principal: mínimo 48px para boa legibilidade à distância",
        "Posicione o QR Code em área de destaque, preferencialmente no terço inferior",
        "Evite imagens com muito texto — priorize mensagem única e CTA claro",
        "Para vídeos: inclua legenda, pois o som está sempre desativado",
      ]},
      { type: "warning", text: "Materiais que não seguirem as dimensões corretas serão recortados automaticamente pela plataforma, podendo prejudicar a mensagem do anúncio." },
    ],
  },
  {
    slug: "relatorios-de-performance-campanha",
    titulo: "Relatórios de performance de campanha",
    tags: ["Analytics", "Relatório"],
    resumo: "Como acessar e interpretar os relatórios de performance das campanhas no Acquafy Media.",
    tempoLeitura: 3,
    conteudo: [
      { type: "p", text: "A plataforma Acquafy Media disponibiliza relatórios detalhados de performance para que anunciantes e parceiros Gold acompanhem o resultado de cada campanha em tempo real." },
      { type: "h2", text: "Métricas disponíveis" },
      { type: "ul", items: [
        "Impressões: número de vezes que o anúncio foi exibido na tela",
        "Visualizações únicas: usuários únicos que viram o anúncio",
        "Scans de QR Code: número de leituras do código",
        "Taxa de conversão: scans / impressões × 100",
        "Horário de pico: momentos com maior engajamento",
        "Performance por ponto: comparativo entre diferentes locais",
      ]},
      { type: "h2", text: "Como acessar os relatórios" },
      { type: "steps", items: [
        { title: "Acesse a plataforma", desc: "Login em media.acquafy.com com sua conta de anunciante ou parceiro." },
        { title: "Vá em Campanhas", desc: "Selecione a campanha desejada na lista." },
        { title: "Toque em Relatórios", desc: "Escolha o período (diário, semanal, mensal ou customizado)." },
        { title: "Exporte os dados", desc: "Baixe o relatório em formato CSV ou PDF para análise offline." },
      ]},
      { type: "tip", text: "Analise os horários de pico para ajustar o conteúdo da campanha conforme o perfil do público em cada momento do dia." },
    ],
  },
]

// ─── Categoria: Parceiros ────────────────────────────────────────────────────────
const artigos_parceiros: ArtigoData[] = [
  {
    slug: "como-se-tornar-parceiro-silver",
    titulo: "Como se tornar um parceiro Silver da Acquafy?",
    tags: ["Silver", "Cadastro"],
    resumo: "Tudo que você precisa saber para se cadastrar como parceiro Silver Acquafy e começar a ganhar comissão por indicações.",
    tempoLeitura: 3,
    conteudo: [
      { type: "p", text: "O programa Silver da Acquafy é o nível de entrada para parceiros. Sem investimento inicial, qualquer pessoa pode se tornar um afiliado e ganhar comissão de 20% sobre cada venda realizada por meio de seu link ou QR Code exclusivo." },
      { type: "h2", text: "Quem pode ser Silver" },
      { type: "ul", items: [
        "Influenciadores digitais e criadores de conteúdo",
        "Consultores de saúde, bem-estar ou tecnologia",
        "Profissionais de vendas autônomos",
        "Parceiros locais com rede de contatos",
        "Qualquer pessoa motivada a indicar e ganhar",
      ]},
      { type: "h2", text: "Como se cadastrar" },
      { type: "steps", items: [
        { title: "Acesse o site Acquafy", desc: "Vá até a página de Parceiros (acquafy.com/parceria)." },
        { title: "Clique em \"Seja Silver\"", desc: "Preencha o formulário com seus dados pessoais e informações de contato." },
        { title: "Aguarde a aprovação", desc: "O time Acquafy avaliará seu cadastro em até 2 dias úteis." },
        { title: "Receba seu kit de afiliado", desc: "Após aprovação, você recebe link exclusivo, QR Code personalizado e materiais de apoio." },
        { title: "Comece a indicar", desc: "Compartilhe seu link nas redes sociais, WhatsApp, e-mail ou pessoalmente." },
      ]},
      { type: "h2", text: "Como funciona a comissão Silver" },
      { type: "ul", items: [
        "20% sobre o valor de cada venda concluída via seu link/QR Code",
        "Comissão confirmada 30 dias após a venda (período antitroca)",
        "Pagamento mensal, no dia 15 do mês seguinte",
        "Valor mínimo para saque: US$ 50",
        "Sem limite máximo de comissão",
      ]},
      { type: "tip", text: "Silver é o caminho mais rápido para entrar no ecossistema Acquafy. Depois de consolidado, você pode evoluir para Gold e operar sua própria rede." },
    ],
  },
  {
    slug: "beneficios-plano-gold-partner",
    titulo: "Quais são os benefícios do plano Gold Partner?",
    tags: ["Gold", "Benefícios"],
    resumo: "Conheça todos os benefícios e oportunidades de receita do plano Gold Partner da Acquafy.",
    tempoLeitura: 4,
    conteudo: [
      { type: "p", text: "O parceiro Gold é o operador do ecossistema Acquafy no seu ponto de hidratação. Além de ganhar comissão sobre vendas, ele monetiza a mídia exibida na tela do purificador, criando uma fonte de receita recorrente." },
      { type: "h2", text: "O que o Gold recebe" },
      { type: "ul", items: [
        "Acquafy Media (purificador Neo com painel de mídia) — entrada a partir de US$ 2.000",
        "Comissão de 20% sobre vendas Neo realizadas via link/QR Code próprio",
        "Receita mensal pela exibição de campanhas publicitárias locais",
        "Acesso à plataforma Acquafy Media para gerenciar campanhas",
        "Suporte dedicado, treinamentos e materiais de apoio",
        "Possibilidade de construir e gerenciar rede de parceiros Silver",
      ]},
      { type: "h2", text: "Diferenciais do Gold em relação ao Silver" },
      { type: "ul", items: [
        "Silver: apenas comissão por indicação de vendas",
        "Gold: comissão de vendas + receita de mídia + gestão de rede Silver",
        "Gold opera um ponto físico de hidratação (o purificador instalado)",
        "Gold pode escalar adquirindo múltiplos equipamentos em diferentes locais",
      ]},
      { type: "h2", text: "Investimento e retorno" },
      { type: "p", text: "O investimento inicial de US$ 2.000 inclui o Acquafy Media (purificador com painel de mídia). A maioria dos parceiros Gold recupera o investimento em 3 a 6 meses, dependendo do fluxo de pessoas no local e da agressividade na captação de anunciantes." },
      { type: "tip", text: "Locais com alto fluxo como academias, clínicas e restaurantes são os pontos mais rentáveis para um parceiro Gold." },
    ],
  },
  {
    slug: "modelo-platinum-distribuidor-regional",
    titulo: "Modelo Platinum: distribuidor regional Acquafy",
    tags: ["Platinum", "Distribuição"],
    resumo: "Entenda como funciona o modelo Platinum da Acquafy para distribuidores regionais e master partners.",
    tempoLeitura: 4,
    conteudo: [
      { type: "p", text: "O Platinum é o nível mais elevado do programa de parceria Acquafy. Voltado para distribuidores regionais e empresas com capacidade de expansão, ele oferece acesso aos produtos com desconto máximo e total liberdade comercial." },
      { type: "h2", text: "Como funciona o modelo Platinum" },
      { type: "ul", items: [
        "Perfil: distribuidor regional / master partner",
        "Compra produtos Neo com 70% de desconto sobre o preço de tabela dos EUA",
        "Modalidade FOB (Free on Board): o Platinum assume frete, impostos e taxas",
        "Revenda livre na sua região — define seus próprios preços",
        "Sem comissão paga à Acquafy: o lucro é a margem de revenda",
      ]},
      { type: "h2", text: "Rede Silver própria" },
      { type: "p", text: "O Platinum pode construir e operar sua própria rede de parceiros Silver, pagando 20% de comissão a esses afiliados pelas vendas que indicarem. Isso cria um efeito multiplicador de escala." },
      { type: "h2", text: "Quem é o Platinum ideal" },
      { type: "ul", items: [
        "Distribuidores de eletrodomésticos ou artigos para saúde",
        "Importadores regionais com infraestrutura logística",
        "Empresas de utilities ou saneamento",
        "Grupos empresariais com presença em múltiplas cidades",
        "Franqueadores regionais",
      ]},
      { type: "h2", text: "Processo de entrada" },
      { type: "p", text: "O modelo Platinum requer avaliação e aprovação prévia pela Acquafy. Entre em contato com o time comercial pelo site para iniciar o processo de qualificação." },
      { type: "warning", text: "O modelo Platinum não paga comissão à Acquafy, mas assume todos os custos de importação, armazenagem e distribuição regional." },
    ],
  },
  {
    slug: "comissoes-por-nivel-de-parceria",
    titulo: "Comissões por nível de parceria (20% a 70%)",
    tags: ["Comissão", "Financeiro"],
    resumo: "Entenda a estrutura completa de comissões e benefícios financeiros para cada nível de parceria Acquafy.",
    tempoLeitura: 3,
    conteudo: [
      { type: "p", text: "A Acquafy oferece uma das estruturas de parceria mais competitivas do setor, com comissões que variam de 20% para afiliados Silver até 70% de margem para distribuidores Platinum." },
      { type: "h2", text: "Silver — 20% de comissão" },
      { type: "ul", items: [
        "20% sobre o valor total de cada venda indicada",
        "Sem investimento inicial necessário",
        "Pagamento mensal após confirmação de 30 dias da venda",
        "Sem limite de comissão mensal",
      ]},
      { type: "h2", text: "Gold — 20% + receita de mídia" },
      { type: "ul", items: [
        "20% sobre vendas Neo via link/QR Code próprio",
        "Receita mensal sobre campanhas exibidas na tela (variável por anunciante)",
        "Receita aumenta com o número de pontos (purificadores) operados",
        "Pode ganhar também das vendas indicadas por Silver da sua rede",
      ]},
      { type: "h2", text: "Platinum — 70% de desconto (margem de revenda)" },
      { type: "ul", items: [
        "Compra produtos com 70% de desconto sobre preço de tabela USA",
        "Define o preço de venda final livremente",
        "Margem potencial: até 70% sobre cada produto vendido",
        "Nenhuma comissão paga à Acquafy — lucro 100% do distribuidor",
      ]},
      { type: "h2", text: "Ciclo de pagamento (Silver e Gold)" },
      { type: "ul", items: [
        "Comissões confirmadas no 30° dia após a venda (prevenção de devoluções)",
        "Pagamento processado até o dia 15 do mês seguinte",
        "Mínimo de US$ 50 para saque",
        "Transferência internacional (SWIFT) ou PIX para clientes brasileiros",
      ]},
      { type: "tip", text: "Silver e Gold podem acumular comissões de múltiplas fontes — quanto mais indicações e pontos ativos, maior o rendimento mensal." },
    ],
  },
  {
    slug: "materiais-de-apoio-vendas-treinamentos",
    titulo: "Materiais de apoio para vendas e treinamentos",
    tags: ["Marketing", "Treinamento"],
    resumo: "Conheça os materiais exclusivos que a Acquafy disponibiliza para parceiros de todos os níveis.",
    tempoLeitura: 3,
    conteudo: [
      { type: "p", text: "A Acquafy disponibiliza um kit completo de materiais de apoio para todos os parceiros, com foco em facilitar as vendas e garantir um onboarding rápido no ecossistema." },
      { type: "h2", text: "Materiais disponíveis" },
      { type: "ul", items: [
        "Catálogo de produtos digitais com especificações e fotos oficiais",
        "Tabela de preços e simulador de comissões",
        "Apresentação comercial editável (PowerPoint e PDF)",
        "Scripts de vendas para abordagem presencial e digital",
        "Modelos de posts para redes sociais (Instagram, LinkedIn, WhatsApp)",
        "Materiais de treinamento em vídeo: produto, plataforma e vendas",
        "Manual técnico de instalação e manutenção",
        "Guias de marca com logos, paleta de cores e tipografia",
      ]},
      { type: "h2", text: "Portal do parceiro" },
      { type: "p", text: "Todos os materiais são acessíveis pelo portal exclusivo de parceiros, disponível após cadastro e aprovação. O portal também concentra relatórios de vendas, comissões e status de pedidos." },
      { type: "h2", text: "Treinamentos disponíveis" },
      { type: "ul", items: [
        "Onboarding inicial: apresentação do produto, modelo de negócio e plataforma",
        "Treinamento de vendas: como abordar clientes, superar objeções e fechar",
        "Treinamento técnico: instalação, configuração e manutenção básica",
        "Treinamento Acquafy Media: gestão de campanhas e captação de anunciantes",
      ]},
      { type: "tip", text: "Parceiros que completam o treinamento de onboarding têm, em média, 2× mais conversões nos primeiros 30 dias de operação." },
    ],
  },
  {
    slug: "operar-rede-silver-sendo-gold-partner",
    titulo: "Como operar a rede Silver sendo um Gold Partner?",
    tags: ["Gold", "Rede"],
    resumo: "Aprenda como um parceiro Gold pode recrutar e gerenciar afiliados Silver para escalar seus resultados.",
    tempoLeitura: 3,
    conteudo: [
      { type: "p", text: "Um dos grandes diferenciais do plano Gold é a possibilidade de construir uma rede de afiliados Silver. Ao recrutar e apoiar Silver partners, o Gold expande seu alcance de vendas sem precisar atender pessoalmente cada cliente." },
      { type: "h2", text: "Como funciona a rede Silver do Gold" },
      { type: "ul", items: [
        "O Gold recruta Silver affiliados e os vincula à sua conta",
        "Cada Silver recebe um link e QR Code exclusivos rastreados",
        "Quando um Silver faz uma venda, o Gold rastreia o resultado via plataforma",
        "O Gold paga 20% de comissão ao Silver sobre a venda concluída",
        "O Gold também pode receber comissão da Acquafy pelas vendas da rede",
      ]},
      { type: "h2", text: "Por que construir uma rede Silver" },
      { type: "ul", items: [
        "Multiplicação de ponto de venda sem aumento de custo fixo",
        "Silver partners trazem suas próprias redes de contato",
        "O Gold gerencia, treina e apoia a rede via portal",
        "Receita escalável: mais Silver → mais vendas → mais comissão",
      ]},
      { type: "h2", text: "Gestão da rede via plataforma" },
      { type: "steps", items: [
        { title: "Recrute Silver partners", desc: "Convide pessoas do seu contato para o programa de afiliados." },
        { title: "Vincule-os à sua conta Gold", desc: "No portal, gere o convite exclusivo que vincula o Silver à sua rede." },
        { title: "Acompanhe a performance", desc: "Veja em tempo real as indicações, vendas e comissões de cada Silver." },
        { title: "Pague as comissões", desc: "O portal calcula automaticamente os valores devidos a cada Silver ao final do ciclo." },
      ]},
      { type: "tip", text: "Gold partners com redes Silver ativas de 10 ou mais afiliados alcançam resultados de receita que equivalem a múltiplos pontos de hidratação físicos." },
    ],
  },
]

// ─── Categoria: Faturamento ──────────────────────────────────────────────────────
const artigos_faturamento: ArtigoData[] = [
  {
    slug: "como-emitir-segunda-via-de-fatura",
    titulo: "Como emitir a segunda via de fatura?",
    tags: ["Fatura", "Financeiro"],
    resumo: "Passo a passo para solicitar e baixar a segunda via de fatura no portal Acquafy.",
    tempoLeitura: 2,
    conteudo: [
      { type: "p", text: "Caso você precise de uma cópia da sua fatura — seja para reembolso, declaração fiscal ou registro contábil —, é possível emiti-la diretamente pelo portal Acquafy." },
      { type: "h2", text: "Como emitir a segunda via" },
      { type: "steps", items: [
        { title: "Acesse o portal Acquafy", desc: "Entre em portal.acquafy.com com seu e-mail e senha cadastrados." },
        { title: "Vá em \"Financeiro\"", desc: "No menu lateral, selecione a seção Financeiro ou Cobranças." },
        { title: "Selecione \"Faturas\"", desc: "Visualize a lista de faturas emitidas com data, valor e status." },
        { title: "Localize a fatura desejada", desc: "Use os filtros de data ou número da fatura para encontrá-la rapidamente." },
        { title: "Clique em \"Segunda via\"", desc: "Faça o download em PDF ou solicite o reenvio por e-mail." },
      ]},
      { type: "h2", text: "Não encontrou sua fatura?" },
      { type: "ul", items: [
        "Verifique se está logado com o e-mail correto",
        "A fatura pode levar até 24h para aparecer após confirmação do pagamento",
        "Para pagamentos internacionais, o documento pode ser chamado de \"Invoice\"",
        "Se persistir, entre em contato pelo suporte informando o número do pedido",
      ]},
      { type: "tip", text: "Para receber automaticamente as faturas por e-mail, ative a opção \"Enviar fatura automaticamente\" nas configurações do portal." },
    ],
  },
  {
    slug: "prazo-recebimento-comissoes",
    titulo: "Prazo para recebimento de comissões",
    tags: ["Comissão", "Pagamento"],
    resumo: "Entenda quando e como as comissões de parceiros Silver e Gold são pagas.",
    tempoLeitura: 2,
    conteudo: [
      { type: "p", text: "As comissões dos parceiros Silver e Gold seguem um ciclo estruturado para garantir que apenas vendas confirmadas e não devolvidas sejam incluídas no pagamento." },
      { type: "h2", text: "Ciclo de confirmação" },
      { type: "ul", items: [
        "A venda é registrada assim que o pagamento do cliente é confirmado",
        "Período de carência: 30 dias para possíveis devoluções ou contestações",
        "Após 30 dias sem contestação, a comissão é confirmada e entra na fila de pagamento",
      ]},
      { type: "h2", text: "Ciclo de pagamento" },
      { type: "ul", items: [
        "As comissões confirmadas são pagas mensalmente",
        "Data de pagamento: até o dia 15 do mês seguinte ao fechamento do ciclo",
        "Exemplo: comissão confirmada em março → pagamento até 15 de abril",
        "Valor mínimo para saque: US$ 50 acumulados",
        "Abaixo do mínimo: saldo é acumulado para o próximo ciclo",
      ]},
      { type: "h2", text: "Formas de recebimento" },
      { type: "ul", items: [
        "Transferência bancária internacional (SWIFT/IBAN) para parceiros fora do Brasil",
        "PIX para parceiros com conta bancária no Brasil",
        "Prazo de processamento: 3 a 5 dias úteis após o pagamento ser processado",
      ]},
      { type: "warning", text: "Certifique-se de manter seus dados bancários atualizados no portal para evitar atrasos no recebimento." },
    ],
  },
  {
    slug: "formas-de-pagamento-aceitas",
    titulo: "Formas de pagamento aceitas pela Acquafy",
    tags: ["Pagamento", "Métodos"],
    resumo: "Conheça todas as formas de pagamento disponíveis para compra de produtos e serviços Acquafy.",
    tempoLeitura: 2,
    conteudo: [
      { type: "p", text: "A Acquafy aceita as principais formas de pagamento para facilitar a compra em qualquer país onde opera." },
      { type: "h2", text: "Pagamento internacional" },
      { type: "ul", items: [
        "Cartão de crédito: Visa, Mastercard e American Express",
        "Cartão de débito internacional",
        "Transferência bancária internacional (SWIFT)",
        "Stripe (processador de pagamentos global)",
        "Parcelamento em cartão disponível para produtos selecionados",
      ]},
      { type: "h2", text: "Pagamento no Brasil" },
      { type: "ul", items: [
        "PIX (confirmação instantânea)",
        "Boleto bancário (confirmação em até 3 dias úteis)",
        "Cartão de crédito nacional (parcelado em até 12x)",
        "Transferência bancária TED/DOC",
      ]},
      { type: "h2", text: "Segurança nos pagamentos" },
      { type: "p", text: "Todas as transações são processadas com criptografia SSL/TLS e conformidade com PCI-DSS. Os dados do cartão nunca são armazenados nos servidores Acquafy." },
      { type: "tip", text: "Para compras acima de US$ 1.000, o pagamento via transferência bancária pode ter tarifas menores do que cartão de crédito." },
    ],
  },
  {
    slug: "acompanhar-status-do-pedido",
    titulo: "Como acompanhar o status do meu pedido?",
    tags: ["Pedido", "Rastreamento"],
    resumo: "Saiba como monitorar em tempo real o status de entrega do seu pedido Acquafy.",
    tempoLeitura: 2,
    conteudo: [
      { type: "p", text: "Após a confirmação do pagamento, seu pedido passa por etapas rastreáveis até a entrega. Você pode acompanhar tudo pelo portal ou pelo e-mail de notificação." },
      { type: "h2", text: "Etapas do pedido" },
      { type: "ul", items: [
        "Aguardando pagamento: pedido criado, aguardando confirmação financeira",
        "Confirmado: pagamento aprovado, pedido em processamento",
        "Em preparação: produto sendo separado e embalado no armazém",
        "Enviado: produto despachado, código de rastreio disponível",
        "Em trânsito: em transporte pela transportadora parceira",
        "Entregue: confirmação de entrega no endereço cadastrado",
      ]},
      { type: "h2", text: "Como acompanhar" },
      { type: "steps", items: [
        { title: "Acesse o portal Acquafy", desc: "Login em portal.acquafy.com." },
        { title: "Vá em \"Pedidos\"", desc: "Lista de todos os seus pedidos com status atual." },
        { title: "Clique no pedido", desc: "Visualize detalhes completos, código de rastreio e histórico de movimentação." },
        { title: "Rastreie pela transportadora", desc: "Use o código fornecido diretamente no site da transportadora para detalhes de localização." },
      ]},
      { type: "p", text: "Notificações automáticas por e-mail e SMS são enviadas a cada mudança de status." },
    ],
  },
  {
    slug: "politica-de-reembolso-e-cancelamento",
    titulo: "Política de reembolso e cancelamento",
    tags: ["Reembolso", "Política"],
    resumo: "Conheça a política de devolução, cancelamento e reembolso da Acquafy para produtos físicos e serviços.",
    tempoLeitura: 3,
    conteudo: [
      { type: "p", text: "A Acquafy respeita o direito do consumidor e oferece uma política clara de devolução e reembolso para garantir sua satisfação." },
      { type: "h2", text: "Devolução de produtos físicos" },
      { type: "ul", items: [
        "Prazo para devolução: 30 dias corridos após a entrega",
        "O produto deve estar em perfeito estado, sem uso e com embalagem original",
        "Solicite a devolução pelo portal ou e-mail de suporte",
        "O frete de retorno é de responsabilidade do cliente (exceto defeito de fábrica)",
      ]},
      { type: "h2", text: "Reembolso" },
      { type: "ul", items: [
        "Prazo de análise: até 5 dias úteis após recebimento do produto devolvido",
        "Reembolso em cartão de crédito: 1 a 2 ciclos de fatura do emissor",
        "Reembolso via PIX ou transferência: até 5 dias úteis após aprovação",
        "Reembolso em forma de crédito na plataforma: disponível imediatamente após aprovação",
      ]},
      { type: "h2", text: "Cancelamento de pedido" },
      { type: "p", text: "Pedidos podem ser cancelados sem custo até o momento do envio. Após o envio, aplica-se a política de devolução." },
      { type: "h2", text: "O que não é reembolsável" },
      { type: "ul", items: [
        "Filtros e consumíveis com embalagem aberta",
        "Serviços digitais ou assinaturas após uso",
        "Produtos com danos causados pelo usuário",
        "Fretes já realizados",
      ]},
      { type: "warning", text: "Para produtos com defeito dentro da garantia, o processo é diferente da devolução padrão. Consulte a política de garantia." },
    ],
  },
  {
    slug: "nota-fiscal-documentacao-fiscal-internacional",
    titulo: "Nota fiscal e documentação fiscal internacional",
    tags: ["Fiscal", "Internacional"],
    resumo: "Entenda a documentação fiscal emitida pela Acquafy para compras no Brasil e no exterior.",
    tempoLeitura: 3,
    conteudo: [
      { type: "p", text: "A Acquafy opera globalmente e emite a documentação fiscal adequada para cada país, garantindo conformidade com as legislações locais." },
      { type: "h2", text: "Clientes no Brasil" },
      { type: "ul", items: [
        "Nota Fiscal Eletrônica (NFe) emitida automaticamente após confirmação do pedido",
        "Enviada ao e-mail cadastrado em até 24h após o envio do produto",
        "DANFE disponível para download no portal de pedidos",
        "Para Pessoa Jurídica: informe o CNPJ no cadastro para emissão correta",
      ]},
      { type: "h2", text: "Clientes internacionais" },
      { type: "ul", items: [
        "Commercial Invoice (fatura comercial) inclusa no envio",
        "Declaração de exportação conforme regulamentação do país de destino",
        "Código HS (Harmonized System) dos produtos informado para liberação alfandegária",
        "Para importações B2B: documentação específica pode ser solicitada via suporte",
      ]},
      { type: "h2", text: "Impostos e taxas de importação" },
      { type: "p", text: "Impostos de importação, ICMS e taxas alfandegárias são de responsabilidade do comprador e variam conforme o país de destino. A Acquafy não se responsabiliza por cobranças realizadas pela alfândega local." },
      { type: "tip", text: "Antes de finalizar uma compra internacional de grande volume, consulte as tarifas de importação do seu país para os NCM/HS Codes correspondentes aos produtos Acquafy." },
    ],
  },
]

// ─── Categoria: Instalação e Manutenção ─────────────────────────────────────────
const artigos_manutencao: ArtigoData[] = [
  {
    slug: "instalacao-passo-a-passo-purificador-neo",
    titulo: "Passo a passo: instalação do purificador Neo",
    tags: ["Instalação", "Tutorial"],
    resumo: "Guia completo para instalar corretamente o purificador Neo em bancada ou parede.",
    tempoLeitura: 5,
    conteudo: [
      { type: "p", text: "A instalação do purificador Neo é projetada para ser simples e pode ser feita por qualquer pessoa com ferramentas básicas. Siga este guia passo a passo para garantir o funcionamento correto desde o primeiro uso." },
      { type: "h2", text: "Pré-requisitos" },
      { type: "ul", items: [
        "Ponto de água fria com torneira de passe (registro específico para purificador)",
        "Tomada elétrica próxima (110V ou 220V, conforme o modelo adquirido)",
        "Sinal Wi-Fi 5 com boa intensidade no local de instalação",
        "Superfície estável (bancada) ou parede estrutural (instalação de parede)",
      ]},
      { type: "h2", text: "Instalação passo a passo" },
      { type: "steps", items: [
        { title: "Escolha o local ideal", desc: "Próximo à pia, com acesso à rede elétrica e sem exposição direta ao sol." },
        { title: "Feche o registro geral de água", desc: "Feche o registro da tubulação onde fará a instalação." },
        { title: "Instale a torneira de passe", desc: "Encaixe o registro específico (incluso na embalagem) na tubulação de água fria." },
        { title: "Conecte a mangueira de entrada", desc: "Encaixe o conector push-fit (1/4\") na torneira de passe. Não requer ferramentas." },
        { title: "Conecte a mangueira de saída", desc: "Para modelos com descarte de água (RO Premium), conecte o tubo de descarte ao ralo mais próximo." },
        { title: "Posicione o purificador", desc: "Apoie em bancada ou fixe na parede usando os suportes inclusos." },
        { title: "Abra o registro de água", desc: "Verifique se há vazamentos em todas as conexões." },
        { title: "Ligue na tomada", desc: "Aguarde o purificador inicializar (LED acende após 10–15 segundos)." },
        { title: "Descarte os primeiros 3L", desc: "Acione a saída de água e descarte os primeiros 3 litros para limpar o sistema." },
        { title: "Configure pelo app", desc: "Abra o Acquafy, conecte via Bluetooth e siga o assistente de configuração de Wi-Fi." },
      ]},
      { type: "warning", text: "Em caso de vazamento após abertura do registro, feche imediatamente a água e revise todas as conexões antes de reabrir." },
    ],
  },
  {
    slug: "frequencia-troca-filtro-365-dias",
    titulo: "Com que frequência trocar o filtro? (365 dias)",
    tags: ["Filtro", "Manutenção"],
    resumo: "Entenda o ciclo de vida dos filtros Neo, como o sistema de monitoramento funciona e como pedir a reposição.",
    tempoLeitura: 3,
    conteudo: [
      { type: "p", text: "Os filtros da linha Neo têm vida útil de 365 dias ou conforme o volume de água filtrada. O sistema de monitoramento inteligente acompanha ambos os parâmetros e avisa com antecedência quando a troca é necessária." },
      { type: "h2", text: "Como o sistema de monitoramento funciona" },
      { type: "ul", items: [
        "O contador de 365 dias começa na data da primeira ativação do purificador",
        "O painel exibe a contagem regressiva em destaque (dias restantes)",
        "O app envia alertas automáticos: 30 dias, 7 dias e 1 dia antes do vencimento",
        "Para modelos com sensores de volume: o filtro pode vencer antes dos 365 dias em caso de uso intenso",
      ]},
      { type: "h2", text: "Por que não ultrapassar os 365 dias" },
      { type: "ul", items: [
        "Filtros vencidos perdem eficiência de purificação progressivamente",
        "Risco de crescimento bacteriano nas membranas",
        "Pode afetar a validade da garantia do produto",
        "A lâmpada UV LED pode não ser suficiente para compensar filtro saturado",
      ]},
      { type: "h2", text: "Como pedir o filtro" },
      { type: "ul", items: [
        "Via app: acesse Filtros > Pedir agora e siga o assistente de reposição inteligente",
        "Via portal Acquafy: seção Acessórios > Filtros compatíveis com seu modelo",
        "Use apenas filtros originais Acquafy para garantir a validade da garantia",
      ]},
      { type: "tip", text: "Ative a Reposição Inteligente no app para que o pedido de filtro seja feito automaticamente com 30 dias de antecedência — você só precisa confirmar." },
    ],
  },
  {
    slug: "como-realizar-limpeza-preventiva",
    titulo: "Como realizar a limpeza preventiva?",
    tags: ["Limpeza", "Preventiva"],
    resumo: "Procedimentos para manter o purificador Neo limpo e em perfeitas condições de operação.",
    tempoLeitura: 4,
    conteudo: [
      { type: "p", text: "A limpeza preventiva regular é fundamental para garantir a qualidade da água, prolongar a vida útil do purificador e manter a higiene do equipamento." },
      { type: "h2", text: "Limpeza externa — mensal" },
      { type: "steps", items: [
        { title: "Desligue o purificador da tomada", desc: "Sempre desligue antes de qualquer procedimento de limpeza." },
        { title: "Limpe o painel touchscreen", desc: "Use pano de microfibra levemente umedecido em água. Nunca use álcool ou solventes sobre o painel." },
        { title: "Limpe o gabinete externo", desc: "Pano seco ou levemente umedecido com água. Para manchas persistentes, use detergente neutro diluído." },
        { title: "Limpe a saída de água", desc: "Remova depósitos de calcário com vinagre branco diluído 1:1 em água. Aplique com cotonete." },
      ]},
      { type: "h2", text: "Sanitização da saída de água — trimestral" },
      { type: "steps", items: [
        { title: "Prepare solução sanitizante", desc: "Misture 1 colher de água sanitária (sem perfume) em 1 litro de água fria." },
        { title: "Aplique na saída", desc: "Com pano umedecido, limpe a bica e área ao redor. Não faça entrar na tubulação interna." },
        { title: "Enxágue com água corrente", desc: "Acione a saída por 10 segundos para remover qualquer resíduo." },
      ]},
      { type: "h2", text: "Limpeza interna — anual (junto com troca do filtro)" },
      { type: "p", text: "A limpeza do circuito interno é realizada automaticamente no processo de ativação do filtro novo, que injeta água de lavagem antes de entrar em operação normal. Não requer intervenção adicional do usuário." },
      { type: "warning", text: "Nunca introduza objetos pela saída de água, nem use produtos abrasivos, alvejantes concentrados ou spray diretamente no painel." },
    ],
  },
  {
    slug: "solucao-problemas-purificador-sem-energia",
    titulo: "Solução de problemas: purificador sem energia",
    tags: ["Problema", "Elétrico"],
    resumo: "Checklist completo para diagnosticar e resolver problemas de energia no purificador Neo.",
    tempoLeitura: 3,
    conteudo: [
      { type: "p", text: "Se o seu purificador Neo não liga ou apresenta falha de energia, siga este checklist antes de acionar o suporte técnico. A maioria dos casos tem solução simples." },
      { type: "h2", text: "Checklist de diagnóstico" },
      { type: "steps", items: [
        { title: "Verifique o cabo de energia", desc: "Certifique-se de que o cabo está firmemente conectado tanto no purificador quanto na tomada." },
        { title: "Teste outra tomada", desc: "Ligue o purificador em outra tomada funcional para descartar problema na instalação elétrica." },
        { title: "Verifique o disjuntor", desc: "Confira o quadro elétrico e reative o disjuntor se estiver desligado." },
        { title: "Confirme a tensão elétrica", desc: "Verifique na etiqueta do produto qual a tensão (110V ou 220V) e se corresponde à sua instalação." },
        { title: "Tente o reset manual", desc: "Pressione e mantenha o botão de energia por 5 segundos. Aguarde 30 segundos e ligue novamente." },
        { title: "Verifique se há superaquecimento", desc: "Se o produto estiver quente ao toque, deixe descansar por 15 minutos antes de religar." },
      ]},
      { type: "h2", text: "Quando chamar o suporte técnico" },
      { type: "ul", items: [
        "O purificador não liga após verificar todas as etapas acima",
        "Há cheiro de queimado ou fumaça ao ligar",
        "O disjuntor desliga repetidamente ao ligar o purificador",
        "O painel acende mas a água não sai",
        "Mensagem de erro persistente no display após reset",
      ]},
      { type: "warning", text: "Nunca tente abrir o purificador para reparos internos sem autorização técnica. Isso anula a garantia e pode apresentar risco elétrico." },
    ],
  },
  {
    slug: "troca-filtro-reposicao-inteligente-via-app",
    titulo: "Troca do filtro: reposição inteligente via app",
    tags: ["Filtro", "App"],
    resumo: "Como usar o recurso de Reposição Inteligente do app Acquafy para nunca ficar sem filtro.",
    tempoLeitura: 3,
    conteudo: [
      { type: "p", text: "O recurso de Reposição Inteligente do aplicativo Acquafy automatiza o processo de compra do filtro, garantindo que o novo filtro chegue antes do vencimento do atual." },
      { type: "h2", text: "Como ativar a Reposição Inteligente" },
      { type: "steps", items: [
        { title: "Abra o app Acquafy", desc: "Faça login na sua conta." },
        { title: "Vá em Filtros", desc: "Toque no ícone de filtro na barra de navegação inferior." },
        { title: "Selecione seu purificador", desc: "Escolha o dispositivo cuja reposição deseja automatizar." },
        { title: "Ative \"Reposição Inteligente\"", desc: "Toque no interruptor e confirme o endereço de entrega e forma de pagamento." },
        { title: "Configure o prazo de antecedência", desc: "Padrão: pedido automático 30 dias antes do vencimento. Você pode ajustar para 15 ou 45 dias." },
      ]},
      { type: "h2", text: "Como funciona" },
      { type: "ul", items: [
        "Quando o filtro atinge o prazo definido, o app gera um pedido de reposição",
        "Você recebe uma notificação para confirmar o pedido",
        "Após confirmação, o filtro é enviado normalmente com rastreamento",
        "Se não confirmar em 48h, o pedido é cancelado automaticamente",
      ]},
      { type: "h2", text: "Como instalar o filtro novo" },
      { type: "steps", items: [
        { title: "Desligue o purificador", desc: "Desconecte da tomada antes de qualquer manuseio." },
        { title: "Feche o registro de água", desc: "Evite vazamentos durante a troca." },
        { title: "Remova o filtro antigo", desc: "Gire no sentido anti-horário até soltar. Use luva para higiene." },
        { title: "Instale o filtro novo", desc: "Encaixe e gire no sentido horário até travar." },
        { title: "Abra o registro e ligue o purificador", desc: "O sistema irá identificar o novo filtro automaticamente e zerar o contador." },
        { title: "Descarte 1L de água", desc: "Primeiros litros de ativação do filtro novo devem ser descartados." },
      ]},
      { type: "tip", text: "Guarde sempre o filtro novo em local fresco e sem umidade até o momento da instalação." },
    ],
  },
  {
    slug: "manutencao-reservatorio-componentes-internos",
    titulo: "Manutenção do reservatório e componentes internos",
    tags: ["Manutenção", "Hardware"],
    resumo: "Procedimentos de manutenção para o reservatório de água e componentes internos do purificador Neo.",
    tempoLeitura: 4,
    conteudo: [
      { type: "p", text: "Nos modelos com reservatório interno (FIT, TOUCH, PLUS, ULTRA, MAX e Premium), a manutenção periódica do reservatório e dos componentes internos é essencial para garantir qualidade de água e durabilidade do equipamento." },
      { type: "h2", text: "Reservatório interno — limpeza trimestral" },
      { type: "steps", items: [
        { title: "Desligue e desconecte da tomada", desc: "Segurança sempre em primeiro lugar." },
        { title: "Esvazie o reservatório", desc: "Abra a saída de frio e deixe drenar completamente." },
        { title: "Prepare solução de limpeza", desc: "100ml de vinagre branco em 1L de água fria ou produto específico para reservatórios alimentares." },
        { title: "Preencha com a solução", desc: "Feche a saída e alimente o reservatório pela entrada de água usando a solução." },
        { title: "Aguarde 20 minutos", desc: "Deixe a solução agir sobre o interior." },
        { title: "Drene e enxágue 3 vezes", desc: "Abra a saída e drene. Repita com água pura até não restar cheiro." },
      ]},
      { type: "h2", text: "Lâmpada UV LED — verificação anual" },
      { type: "ul", items: [
        "Vida útil: aproximadamente 10.000 horas de operação",
        "O app indica quando a lâmpada precisa de substituição",
        "A troca deve ser realizada por técnico autorizado",
        "Solicite agendamento pelo portal de suporte",
      ]},
      { type: "h2", text: "Membrana UF — substituição junto com filtro" },
      { type: "p", text: "A membrana de Ultrafiltração (UF) é parte integrante do kit de filtros. Ao substituir o filtro anualmente, a membrana UF também é renovada, sem necessidade de procedimento separado." },
      { type: "h2", text: "Manutenção profissional — recomendada anualmente" },
      { type: "ul", items: [
        "Inspeção completa de conexões e vedações",
        "Verificação do sistema elétrico e painel",
        "Calibração dos sensores IoT",
        "Limpeza profunda do circuito interno",
        "Agende pelo portal de suporte ou pelo app",
      ]},
      { type: "tip", text: "A manutenção profissional anual é especialmente importante para modelos em locais de alto fluxo (academias, restaurantes), onde o desgaste é maior." },
    ],
  },
]

// ─── Catálogo completo ──────────────────────────────────────────────────────────
export const CATEGORIAS: CategoriaData[] = [
  {
    slug: "produtos",
    titulo: "Produtos",
    descricao: "Informações sobre Linha Neo, Acquafy Media, filtros, acessórios e especificações.",
    cor: "#0233c3",
    corBg: "#0233c318",
    icon: "/figma-assets/d2eb2d02-8be8-4653-ae2c-174d7b564294.svg",
    aspectW: 642.7,
    aspectH: 630.7,
    artigos: artigos_produtos,
  },
  {
    slug: "app-ai-iot",
    titulo: "App + AI + IoT",
    descricao: "Suporte ao aplicativo, conectividade, sensores, IA e integração IoT.",
    cor: "#0569ff",
    corBg: "#0569ff18",
    icon: "/figma-assets/917d2d21-0553-4643-b0fc-73f9af2a9756.svg",
    aspectW: 21,
    aspectH: 30,
    artigos: artigos_app_ai_iot,
  },
  {
    slug: "media-network",
    titulo: "Media Network",
    descricao: "Dúvidas sobre anúncios, QR Codes, campanhas e receita recorrente.",
    cor: "#9f3df5",
    corBg: "#9f3df518",
    icon: "/figma-assets/b509f7df-2405-4256-b220-011fd8dd5592.svg",
    aspectW: 30,
    aspectH: 30,
    artigos: artigos_media_network,
  },
  {
    slug: "parceiros",
    titulo: "Parceiros",
    descricao: "Informações para parceiros, Gold Partner, contratos e materiais de apoio.",
    cor: "#1f2e91",
    corBg: "#1f2e9118",
    icon: "/figma-assets/14a82867-83cc-431e-98b4-3603d8945aab.svg",
    aspectW: 1125,
    aspectH: 1078,
    artigos: artigos_parceiros,
  },
  {
    slug: "faturamento",
    titulo: "Faturamento",
    descricao: "Dúvidas sobre pedidos, faturas, pagamentos e comissões.",
    cor: "#36ae5c",
    corBg: "#36ae5c18",
    icon: "/figma-assets/00faff7b-84c5-43b7-aa62-455049b87f58.svg",
    aspectW: 33.3,
    aspectH: 30,
    artigos: artigos_faturamento,
  },
  {
    slug: "instalacao-e-manutencao",
    titulo: "Instalação e Manutenção",
    descricao: "Instalação, manutenção preventiva, limpeza e suporte técnico.",
    cor: "#dfa727",
    corBg: "#dfa72718",
    icon: "/figma-assets/ef3ff887-7eee-4719-b173-bde7b98d9984.svg",
    aspectW: 30,
    aspectH: 30,
    artigos: artigos_manutencao,
  },
]

// ─── Helpers ────────────────────────────────────────────────────────────────────
export function getCategoriaBySlug(slug: string): CategoriaData | undefined {
  return CATEGORIAS.find((c) => c.slug === slug)
}

export function getArtigoBySlug(catSlug: string, artigoSlug: string): { artigo: ArtigoData; categoria: CategoriaData } | undefined {
  const categoria = getCategoriaBySlug(catSlug)
  if (!categoria) return undefined
  const artigo = categoria.artigos.find((a) => a.slug === artigoSlug)
  if (!artigo) return undefined
  return { artigo, categoria }
}
